version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: mkdir mitesh
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: mkdir Savani
      